### PR TITLE
Update dependencies of packages affected by `functors` migration

### PR DESCRIPTION
**Pull request by JordanMartinez**
Part of purescript/purescript-profunctor#23

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Need to update `profunctor-lenses` to use new module name of `Costar`. Fix in https://github.com/purescript-contrib/purescript-profunctor-lenses/pull/127:
```
[1/1 ModuleNotFound] src/profunctor-lenses/main/src/Data/Lens/Grate.purs:24:1

  24  import Data.Profunctor.Costar (Costar(..))
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  Module Data.Profunctor.Costar was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

           Src   Lib   All
Warnings   0     0     0  
Errors     1     0     1  
[error] Failed to build.
Error: Process completed with exit code 1.
```

**Comment by rhendric** [comment]
Also, `"contravariant"` should be dropped from `profunctor`'s list of dependencies.

**Comment by JordanMartinez** [comment]
Thanks!

**Comment by JordanMartinez** [comment]
Next error was due to `css`. Fix made in https://github.com/purescript-contrib/purescript-css/pull/129

**Comment by JordanMartinez** [comment]
`css` error can't be fixed until `lookup` is exported in `foldable-traversable`. Fix for that here: https://github.com/purescript/purescript-foldable-traversable/pull/133

**Comment by JordanMartinez** [comment]
We have a sort of chicken-and-egg problem here... The `prepare-0.14` package set does not yet include the updated dependency graphs, which is what this PR fixes. Thus, when CI in `css` attempts to build, it's using the dependency graph before we did the `functors` migration. To get `css`' CI to pass, we have to merge this PR first, even if this PR's CI doesn't currently build. It's either that or dropping `css` and all other packages that don't build in this PR, only to re-add them later.

**Comment by rhendric** [comment]
Can the set in this PR reference the branch on which `css`'s PR currently lives? Then we can keep finding libraries, creating PRs for them, and referencing them until this PR passes, at which point we can merge the library PRs even though they aren't green because this PR demonstrates that they *would* be green, and then this PR can point to the main branches again and finally merge?

**Comment by JordanMartinez** [comment]
> Can the set in this PR reference the branch on which css's PR currently lives? Then we can keep finding libraries, creating PRs for them, and referencing them until this PR passes, at which point we can merge the library PRs even though they aren't green because this PR demonstrates that they would be green, and then this PR can point to the main branches again and finally merge?

Hey! That's smart! And I've already tested this locally and it works fine once `css` gets fixed, so let's do it!

**Comment by JordanMartinez** [comment]
I'll merge this PR once one of the core contributors approve this.

**Review by thomashoneyman — APPROVED** [review]

**Pull request merged**
