### PR TITLE
Automatically generate packages.json file on pull requests

### PR DESCRIPTION
**Pull request by thomashoneyman**
This PR modifies the GitHub Actions pipeline to update and commit (if necessary) the `packages.json` file.

With this change, contributors only need to update the relevant `.dhall` files (which can often be done strictly through the GitHub UI, minimizing the effort required). If the update changes the packages.json file then it will automatically be committed to their branch. If it does not, then nothing will be committed. Either way the tests will still run -- they don't rely on the packages.json file in any case.

You can see an example of this action working in this commit, performed by the GitHub Actions user: https://github.com/purescript/package-sets/commit/77303d42c6ace57e2d5f04fc9d9856856232ef87

I _believe_ this should work on any pull request to the repository, but I can't test that until this is merged and a PR from an account without access to this repository makes a pull request. So I propose:

1. If this generally looks good then we merge it
2. Another member of the Contributors org who doesn't have access to this repository updates a package
3. We verify that this CI does properly commit to their branch
4. If it does not, then I revert this commit to go back to the previous CI process.

@f-f I'm not sure what README updates to make to help casual contributors know that they just have to update the relevant `.dhall` file for their changes. Do you have any suggestions?

### CODE REVIEW

**Comment by thomashoneyman** [comment]
Whew! OK, after some trial and error there this is working properly and is ready for review.

**Comment by thomashoneyman** [comment]
If this is working correctly, then there should be no additional commit after `a7078a9` and the tests should pass.

**Comment by thomashoneyman** [comment]
😓 _Now_ it looks acceptable. These commands are fiddly!

**Review by f-f — APPROVED** [review]
@thomashoneyman looks great! :clap: 

I have two small notes:
- we should probably update the [contributing instructions](https://github.com/purescript/package-sets/blob/master/CONTRIBUTING.md#how-to-add-a-package-to-the-set) to remove all mentions of `nix`, and generally instruct people to only change the `dhall` files
- and it looks like `make ci` is now unused since we only use the more granular targets in the CI workflow, so it could be removed?

**Comment by f-f** [comment]
@thomashoneyman I'll go ahead and merge this so we can see if it works on #770

**Comment by andys8** [comment]
@thomashoneyman based solely on the commit history and ci runs, it looks like adding commits on forks is/was a bit of a hassle. One idea that came to my mind, is to generate and commit the `package.json` update only on `push` to `master` events on CI.

**Comment by thomashoneyman** [comment]
@andsy8 the main reason to try and include the generated packages.json file in the pull request is because then subsequent PRs into master don't have to pull the changes and re-run verification before they can be merged to master. Right now if a package merges in, and the packages.json file changes, then the next package to go in has to merge master, run checks, and then merge.

**Pull request merged**
