### PR TITLE
license added

### PR DESCRIPTION
**Pull request by Ebmtranceboy**

### CODE REVIEW

**Comment by maxdeviant** [comment]
Hey @Ebmtranceboy, it looks like CI is failing because you need to apply the changes here as well: https://github.com/purescript/package-sets/blob/2d15cde46ad7d2d7a247aa92cf776dacbc63a161/src/groups/ebmtranceboy.dhall#L6-L10

(The `packages.json` is just an artifact we generate from the Dhall files).

**Review by Ebmtranceboy — COMMENTED** [review]
updating tag in dhall file

**Comment by maxdeviant** [comment]
> updating tag in dhall file

Now it looks like it's failing because a new entry for `geometry-plane` was added to `packages.json` instead of updating the existing entry.

I think if you fix that then CI should pass.

**Comment by Ebmtranceboy** [comment]
I tried to remove the previous entry, then to remove every reference (hoping the generated version would complete). Now, I'm clueless. Maybe generate a new tag ?

**Comment by f-f** [comment]
Hi @Ebmtranceboy! The usual workflow for editing the files here is that contributors edit the `.dhall` files, and then generate the `packages.json` by running `nix-shell --run 'make'`. Could you try that?

**Comment by Ebmtranceboy** [comment]
Hey thanks @f-f  and @maxdeviant . Totally forgotten about nix make ;) Sorry !

**Pull request merged**
