### PR TITLE
Add webgl bindings

### PR DESCRIPTION
**Pull request by btrepp**
Adds the webgl package and it's dependencies.
Foreign-clone is concerning, but this is the simplest way
to add it into the package-set

I haven't forked any of the repos, preferring to add them as is.

### CODE REVIEW

**Comment by hdgarrood** [comment]
IIRC `foreign-clone` exists because the maintainer of the webgl bindings preferred the design of an older version of the `foreign` library, and just took that older version and published it as `foreign-clone`.

**Comment by btrepp** [comment]
@justinwoo I agree with the sentiment. I've only just started on the purescript journey and wanted to help contribute.

What is needed to get this curated-worthly. Just updating the deps to use foreign instead of foreign-clone?

Maybe @jutaro can comment?. This is all his good work. It would be nice to have webGL easily accessibly in the curated package set :).

**Comment by AlexMouton** [comment]
@btrepp I have been working on jutaros good webgl/matrix/vector in my forks as well.
If you're digging in please take a look.  Jutaro has been unresponsive to my PRs, at least, since Dec

**Comment by AlexMouton** [comment]
(I Just got my continuation of vector/matrix/webgl into a package set here: https://github.com/AlexMouton/package-sets#mouton

**Comment by btrepp** [comment]
Tracing through the deps (assuming the bower.json was correct). It looks like extensions -> foreign-clone and the only place the CForiegn is used is to call 'stringify'.

@AlexMouton would you be okay maintaining a fork of webgl/matrix/vector?. I could probably give a shot at modifying 'extensions' so it doesn't depend on foreign-clone.

**Pull request closed without merging**
