### PR TITLE
Add react-testing-library

### PR DESCRIPTION
**Pull request by i-am-the-slime**
Adds react-testing-library as hopefully the last step of i-am-the-slime/purescript-react-testing-library#4

### CODE REVIEW

**Comment by f-f** [comment]
@thomashoneyman any idea why the checkout is failing here? :thinking:

**Comment by i-am-the-slime** [comment]
I think it's because I didn't format.

**Comment by thomashoneyman** [comment]
Sorry about the delay, @i-am-the-slime, I made a mistake with our new CI workflow which generates that packages.json file for you. In the future you should only have to edit your `.dhall` file directly and the rest is taken care of.

**Comment by i-am-the-slime** [comment]
Sure, no problem! Thanks for doing this!

**Comment by ursi** [comment]
@thomashoneyman nice! I will try redoing my current failing PR.

**Pull request merged**
