### PR TITLE
Add @maxdeviant's packages

### PR DESCRIPTION
**Pull request by maxdeviant**
This PR adds the following packages of mine to the package set:

- [heckin](https://pursuit.purescript.org/packages/purescript-heckin/1.0.3)
- [npm-package-json](https://pursuit.purescript.org/packages/purescript-npm-package-json/1.2.0)
- [which](https://pursuit.purescript.org/packages/purescript-which/0.1.0)

### CODE REVIEW

**Comment by thomashoneyman** [comment]
@maxdeviant Do you mind merging master into this branch? Once CI builds I should be ready to merge.

**Comment by maxdeviant** [comment]
@thomashoneyman Sure thing!

Also, based on what you said [here](https://github.com/purescript-contrib/purescript-options/pull/37#discussion_r495645384) I'm guessing I should remove `psci-support` as a dependency from these packages?

**Comment by thomashoneyman** [comment]
It's not strictly necessary, but consumers of your packages probably don't need to pull in `psci-support` as well. I'd only include the packages necessary for your libraries to work correctly and elide any test / dev / build dependencies.

When the registry (https://github.com/purescript/registry) is ready to go this will be a lot smoother and you won't have to think about the spago.dhall files being added here vs. what's used in your repositories.

**Comment by thomashoneyman** [comment]
@maxdeviant Let me know if you'd like to make that change or whether you'd like for me to merge this.

**Comment by maxdeviant** [comment]
@thomashoneyman I think I'll just leave it for now (my guess is most people are going to have `psci-support` in their dependency tree anyways).

**Pull request merged**
