### PR TITLE
Add packages from thomashoneyman, matthew-hilty, awakesecurity, citiz…

### PR DESCRIPTION
**Pull request by thomashoneyman**
Adds a number of packages to the package set from several users. 👋

### CODE REVIEW

**Comment by thomashoneyman** [comment]
I'm not entirely sure what to do about dev dependencies (`debug`, `psci-support`) and have included them for now.

**Comment by justinwoo** [comment]
are they in the bower dependencies? seems like they should be cleanedup

**Comment by thomashoneyman** [comment]
No, they're not in the bower dependencies -- they're in the `devDependencies`. I've removed them.

**Comment by justinwoo** [comment]
thanks

**Pull request merged**
