### PR TITLE
Update for argonaut-codecs

### PR DESCRIPTION
**Pull request by thomashoneyman**
This PR updates the package set to accommodate the change to argonaut-codecs to introduce typed errors.

Currently, these libraries are being removed from the package set. As noted in #642 each of these (except trout-client, which is waiting on an update to hyper) have had pull requests open for 11 days at the time this PR was opened.

- [ ] option (@joneshf)
- [ ] polyform-validators (@paluh)
- [x] refined (@danieljharvey)
- [x] tolerant-argonaut (@matthew-hilty)
- [x] trout-client

This isn't urgent to merge because most folks are on the older package set. However, Bower users are going to be installing incompatible versions of the other ~15 libraries that have been updated, so it's still good to merge this at some point in the next week or two.

### CODE REVIEW

**Comment by danieljharvey** [comment]
Have just released v1.0.0 of `refined` that uses the new Argonaut.

**Comment by thomashoneyman** [comment]
Thanks! There are now only 4 libraries in the package set affected by the change.

**Comment by thomashoneyman** [comment]
We're down to 3 libraries affected. I suggest we merge this in a week (next Friday), but I understand if we need to wait a little longer to try and get _all_ the libraries in.

**Comment by thomashoneyman** [comment]
@f-f The only remaining libraries affected are polyform-validators (@paluh) and option (@joneshf). I think this should be merged this Friday, but I am open to pushing it back another week.

**Comment by f-f** [comment]
@thomashoneyman nothing has moved in a week, so I'd say we could go ahead with this?

**Comment by thomashoneyman** [comment]
Yes, let’s do it!

**Pull request merged**
