### PR TITLE
Add package queue

### PR DESCRIPTION
**Pull request by flip111**
I don't know why all the source files got reindented it's something the tools are doing. I just build the latest version of dhall and psc-package from source.

### CODE REVIEW

**Comment by f-f** [comment]
Hi @flip111! It looks like you're using different versions from CI (I'm working to upgrade all CI to latest) and that's causing lots of reformatting, could you run `nix-shell --command='make'`?

**Comment by flip111** [comment]
I get an error with this command

```
checking for references to /build/ in /nix/store/bmb8shz4djbsv7mivfw55hb50j0napma-spago...
dhall: 
Error: Invalid input

src/mkPackage.dhall:4:17:
  |
4 | → { dependencies, repo, version } : ./Package.dhall
  |                 ^
unexpected ','
expecting :, =, or whitespace

formatted dhall files
generated to packages.json
```

**Comment by f-f** [comment]
@flip111 can you reset that `mkPackage` file to its `master` version?

**Comment by flip111** [comment]
It was already on the version of `master` unmodified

**Comment by f-f** [comment]
@flip111 I updated the tools to their latest versions in `nix-shell`, could you rebase this branch on `master` and run `nix-shell --command make` again?

**Comment by flip111** [comment]
```
» git pull --rebase origin master
From https://github.com/flip111/package-sets
 * branch            master     -> FETCH_HEAD
Current branch patch-1 is up to date.
```

i rebased but nothing changed because i still get the same error

```
dhall: 
Error: Invalid input

src/mkPackage.dhall:4:17:
  |
4 | → { dependencies, repo, version } : ./Package.dhall
  |                 ^
unexpected ','
expecting :, =, or whitespace

formatted dhall files
generated to packages.json
```

**Comment by f-f** [comment]
@flip111 I deleted `mkPackage` in #591, while your diff still shows it, so maybe you didn't pull `master` before rebasing?

**Comment by flip111** [comment]
Oh i think i only pulled master from my own remote fork and not from the original.

I tried to rebase but i'm totally lost now with git.

I will open another PR, it's easier for me.

**Pull request closed without merging**
