### PR TITLE
To lowercase

### PR DESCRIPTION
**Pull request by oreshinya**

### CODE REVIEW

**Comment by justinwoo** [comment]
it should be fine to leave these as is, only the filenames need to be lower cased (because of OSX users)

**Comment by f-f** [comment]
Yes, and also this is a bug in the bot, so that's the only thing that should be patched

**Comment by oreshinya** [comment]
Because I felt sorry to make you feel that you have to fix it soon, I did it for the current curator's problem.
Sorry, I close it.

**Comment by f-f** [comment]
@oreshinya no worries, I already fixed the bug in the Curator so the next updates should be automated. And I appreciated, thanks 🙂

**Pull request closed without merging**
