### PR TITLE
fix(#856): add memoize, update optparse

### PR DESCRIPTION
**Pull request by srghma**

### CODE REVIEW

**Comment by srghma** [comment]
@jvliwanag, @paluh , @flip111 added https://github.com/purescript-codegen/purescript-ps-cst

**Comment by thomashoneyman** [comment]
You’ll also need to run nix-shell —run ‘make’ and commit the result. Thanks!

**Comment by srghma** [comment]
thx, didnt see this

**Comment by srghma** [comment]
dont understand why it errors

```
Found some packages not in the registry:
[ "open-folds", "open-memoize", "open-pairing", "ps-cst", "record-extra-srghma", "url-regex-safe" ]
```

**Comment by srghma** [comment]
I did `spago verify open-folds && spago verify open-memoize && spago verify open-pairing && spago verify ps-cst && spago verify record-extra-srghma && spago verify url-regex-safe`

**Comment by f-f** [comment]
@srghma you added these packages here to `package-sets`, but they need to be added [to this list in the Registry first](https://github.com/purescript/registry/blob/master/new-packages.json)

**Comment by srghma** [comment]
@f-f could we merge, please

**Comment by f-f** [comment]
@srghma [as listed in our Contributing documentation](https://github.com/purescript/package-sets/blob/master/CONTRIBUTING.md#general), all the packages in the set must be published with `pulp publish`, which requires a `bower.json` to be present. Some of the packages you are adding here do not contain this file. Can you publish new versions using `pulp`?

**Comment by srghma** [comment]
@f-f done, pls

**Review by f-f — APPROVED** [review]
Great, thank you!

**Pull request merged**
