### PR TITLE
Add axios

### PR DESCRIPTION
**Pull request by andys8**
Adding https://github.com/iarthstar/purescript-axios

### CODE REVIEW

**Comment by andys8** [comment]
CI failing with:

```
[error] Installation failed
[error] Error:
[error] Codec.Compression.Zlib: compressed data stream format error (incorrect header check)
make: *** [Makefile:24: ci] Error 1
##[error]Process completed with exit code 2.
```

**Comment by elliotdavies** [comment]
@andys8 There was a temporary blip with one of the packages in the set, but if you (or someone else) can re-run the CI that error should be resolved 🤞

**Comment by andreas-ebot7** [comment]
Pushed both PRs again to trigger rebuild

**Comment by andys8** [comment]
pushed both PRs again to trigger rebuild.

**Review by f-f — APPROVED** [review]
Thanks!

**Pull request merged**
