### PR TITLE
Add debuggest

### PR DESCRIPTION
**Pull request by ursi**

### CODE REVIEW

**Comment by ursi** [comment]
I have no idea what's going wrong here...

**Comment by f-f** [comment]
It looks like CI is failing because the `packages.json` was not updated - could you run `nix-shell --run 'make'` and commit all the files?

**Comment by ursi** [comment]
aaaah of course, forgot to do that. Can't wait till the process gets streamlined lol

**Comment by f-f** [comment]
> Can't wait till the process gets streamlined lol

Same here, same here :smile:

**Pull request merged**
