### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by f-f**

### CODE REVIEW

**Comment by f-f** [comment]
@thomashoneyman the automation seems to work well, except the status doesn't seem to be reported :thinking:

**Comment by thomashoneyman** [comment]
Hm. I guess that’s because the required ‘tests’ check doesn’t run on the last commit (the update package) because it’s committed by the action. I’ll have to see how we can get around this.

**Comment by f-f** [comment]
I think running it on every commit would be harmless: once the Action updates the `packages.json` then it would stop triggering the action to add more commits? (Since the diff will be empty)

**Comment by thomashoneyman** [comment]
@f-f it now re-triggers and runs successfully.

**Comment by thomashoneyman** [comment]
I'm making one more update -- now, the full tests will only be run if the packages.json was unchanged (to avoid burning minutes on the lengthy tests when we know that we're committing and re-running again).

**Comment by thomashoneyman** [comment]
This looks good now. We just need to be careful updating these workflows in the future to make sure we never get into a loop.

**Comment by f-f** [comment]
Looks great, thank you @thomashoneyman! :heart:

**Pull request merged**
