### PR TITLE
Update bucketchain-static to v0.3.0

### PR DESCRIPTION
**Pull request by oreshinya**
Yesterday, I updated this package and released, but Auto PR by bot was not created.
Is bot-flow experimental yet ?

### CODE REVIEW

**Comment by justinwoo** [comment]
Thanks. not entirely sure what went on with the bot, maybe it just missed some other updates

**Comment by f-f** [comment]
@oreshinya yes the bot still has some rough edges. I'll look at the logs to see what's up with it, but it might be the fact that `Bucketchain` is not all lowercase..

**Comment by f-f** [comment]
Yep, that's it. Relevant logs from the bot:
```
Retry 0: fetching commit metadata for 'Bucketchain/purescript-bucketchain-static'..
Found a newer tag for 'bucketchain-static': v0.3.0
No previous PRs found, verifying the addition and eventually committing..
Branch name: spacchettibotti-bucketchain-static-v0.3.0
Could not find file data/package-sets/src/groups/Bucketchain.dhall
```

I'll take a look later to see if it's easy to fix (if you want to take a look, the whole source for it is [here](https://github.com/spacchetti/spago/blob/master/app/Curator.hs))

**Comment by oreshinya** [comment]
OK, I see.
I'll also fix case later, thank you!

**Pull request merged**
