### PR TITLE
Add package queue nr 2

### PR DESCRIPTION
**Pull request by flip111**
Replaces https://github.com/purescript/package-sets/pull/585

### CODE REVIEW

**Comment by flip111** [comment]
This is messed up too.

**Comment by flip111** [comment]
I tried to start a 3rd pull request but when i run nix-shell again another file changes

```
diff --git a/packages.json b/packages.json
index e1f2589..69d946f 100644
--- a/packages.json
+++ b/packages.json
@@ -2571,6 +2571,17 @@
     "repo": "https://github.com/Dretch/purescript-querydsl.git",
     "version": "v0.10.1"
   },
+  "queue": {
+    "dependencies": [
+      "aff",
+      "avar",
+      "console",
+      "foreign-object",
+      "refs"
+    ],
+    "repo": "https://github.com/athanclark/purescript-queue.git",
+    "version": "v8.0.1"
+  },
   "quickcheck": {
     "dependencies": [
       "arrays",
diff --git a/src/groups/athanclark.dhall b/src/groups/athanclark.dhall
index 871dae9..f21b537 100644
--- a/src/groups/athanclark.dhall
+++ b/src/groups/athanclark.dhall
@@ -3,4 +3,9 @@
   , repo = "https://github.com/athanclark/purescript-float32.git"
   , version = "v0.1.1"
   }
+, queue =
+  { dependencies = [ "console", "refs", "aff", "foreign-object", "avar" ]
+  , repo = "https://github.com/athanclark/purescript-queue.git"
+  , version = "v8.0.1"
+  }
 }
diff --git a/src/groups/csicar.dhall b/src/groups/csicar.dhall
index 60c761b..6a85a8d 100644
--- a/src/groups/csicar.dhall
+++ b/src/groups/csicar.dhall
@@ -15,21 +15,21 @@
   , version = "v1.0.0"
   }
 , vectorfield =
-    { dependencies = [ "console", "effect", "group", "prelude", "psci-support" ]
-    , repo = "https://github.com/csicar/purescript-vectorfield.git"
-    , version = "v1.0.1"
-    }
+  { dependencies = [ "console", "effect", "group", "prelude", "psci-support" ]
+  , repo = "https://github.com/csicar/purescript-vectorfield.git"
+  , version = "v1.0.1"
+  }
 , typelevel-peano =
-    { dependencies =
-      [ "unsafe-coerce"
-      , "arrays"
-      , "console"
-      , "effect"
-      , "typelevel-prelude"
-      , "prelude"
-      , "psci-support"
-      ]
-    , repo = "https://github.com/csicar/purescript-typelevel-peano.git"
-    , version = "v0.1.8"
-    }
+  { dependencies =
+    [ "unsafe-coerce"
+    , "arrays"
+    , "console"
+    , "effect"
+    , "typelevel-prelude"
+    , "prelude"
+    , "psci-support"
+    ]
+  , repo = "https://github.com/csicar/purescript-typelevel-peano.git"
+  , version = "v0.1.8"
+  }
 }
```

**Comment by f-f** [comment]
@flip111 yeah that change sounds good, could you commit that? (I think this one needs rebasing too btw)

**Comment by flip111** [comment]
I'm having too much trouble with rebasing. i opened another PR sorry

**Pull request closed without merging**
