### PR TITLE
Add sparkle

### PR DESCRIPTION
**Pull request by sharkdp**
See #101

### CODE REVIEW

**Comment by paf31** [comment]
Thanks!

**Comment by joneshf** [comment]
Is a new release needed in order to reference these packages?

**Comment by paf31** [comment]
Yes, but I think you can reference the SHA hash for now. If not, I can make a tag.

**Comment by joneshf** [comment]
Looks like this PR would need to be merged and released in `psc-package` in order for SHAs to work: https://github.com/purescript/psc-package/pull/45.

**Comment by paf31** [comment]
Okay, can you please try the `psc-0.11.6-09092017` tag?

**Comment by joneshf** [comment]
Works great! Thanks!

**Pull request merged**
