### PR TITLE
Upgrade to 0.14.6

### LINKED ISSUE #1070: Make v0.14.6 package set
I'm not sure how to do this, so I'm requesting such a release.

### PR DESCRIPTION
**Pull request by thomashoneyman**
Closes #1070

### CODE REVIEW

**Comment by thomashoneyman** [comment]
Whoops, forgot we need to update PureScript in `easy-purescript-nix` and then update this repository to use that.

For example:
https://github.com/justinwoo/easy-purescript-nix/pull/170

cc: @toastal would you be willing?

**Comment by JordanMartinez** [comment]
I'm waiting for `v0.14.7` to finish building, and then I'll submit a PR for `easy-purescript-nix`.

**Comment by JordanMartinez** [comment]
This PR is blocked on https://github.com/justinwoo/easy-purescript-nix/pull/185

**Comment by toastal** [comment]
@JordanMartinez 's PR is merged. It was definitely the weekend for me at the time.

**Comment by thomashoneyman** [comment]
@toastal no problem! I’m just used to seeing your update PRs go through 😄 thanks!

**Comment by f-f** [comment]
So should we just bump to 0.14.7 instead?

**Comment by JordanMartinez** [comment]
I was thinking we would do a v0.14.6 package set release, followed immediately by a v0.14.7 one. The fact is, a `v0.14.6` release does exist.

**Pull request merged**
