### PR TITLE
feat: add rxps

### PR DESCRIPTION
**Pull request by waynevanson**
This shouldn't work yet, still waiting for https://github.com/LukaJCB/purescript-rxps/pull/9 to be merged and released as v1.8.0

I had someone star my version of the library, so here we are putting it where it's meant to be.

I put my name as the author so if it pings anyone, it'll ping me.
If @lukajcb doesn't want to maintain this any longer, this PR will do that. Otherwise I'll change it to his details.

### CODE REVIEW

**Comment by f-f** [comment]
@waynevanson we send our pings directly to repositories, so if you're watching it you should get notified.

The name for the group file should instead be the username under which the repo is contained, in this case `LukaJCB`

**Comment by waynevanson** [comment]
> The name for the group file should instead be the username under which the repo is contained, in this case LukaJCB

@f-f Okay thank you. I've spoken to him and he said he'll be happy transfer the rights to me, so I'll change this accordingly when the transfer is complete.

**Comment by waynevanson** [comment]
- Repo ownsership has been transferred to me.
- Added `git tag v1.8.0` and `git push --tags`
- Verified via `make && cd src && spago verify rxps` using `nix-shell`. How good is nix!

**Comment by f-f** [comment]
It looks like CI is failing because the `packages.json` was not updated - could you run `nix-shell --run 'make'` and commit all the files?

**Comment by waynevanson** [comment]
@f-f Done

**Comment by f-f** [comment]
Thank you!

**Pull request merged**
