### PR TITLE
Add sparse-matrices

### PR DESCRIPTION
**Pull request by Ebmtranceboy**

### CODE REVIEW

**Comment by f-f** [comment]
@Ebmtranceboy curiosity: GitHub shows that all the releases have been published today, but also the package is registered on Bower. How did you manage to do that? :smile:

**Comment by Ebmtranceboy** [comment]
@f-f I don't remember exactly but the one that is on Pursuit was the previous version (v1.0.0) whereas this new one is v1.1.0. Is it what you see on Bower? Is it a problem?

**Comment by f-f** [comment]
Not a problem, just curious how that could happen!

**Comment by Ebmtranceboy** [comment]
I registered v1.0.0 on bower around septembre 19, and v1.1.0 yesterday on package-sets. What is odd about it ?

**Pull request merged**
