### PR TITLE
Add purescript-typelevel-peano

### PR DESCRIPTION
**Pull request by mwalkerwells**

### CODE REVIEW

**Comment by f-f** [comment]
Hi @mwalkerwells! It looks like you're using different versions from CI (I'm working to upgrade all CI to latest) and that's causing lots of reformatting, could you run `nix-shell --command='make'`?

**Comment by mwalkerwells** [comment]
Running nix on Catalina is complicated, but I got it working and looks like everything is GTG

**Comment by f-f** [comment]
@mwalkerwells thank you!

**Comment by mwalkerwells** [comment]
Possible to release a new version?

**Comment by f-f** [comment]
Yep, I'll cut a new one as soon as we merge #591, #590, #585

**Comment by mwalkerwells** [comment]
Sounds great, thanks!

**Comment by f-f** [comment]
You're welcome :slightly_smiling_face:

**Comment by f-f** [comment]
@mwalkerwells https://github.com/purescript/package-sets/releases/tag/psc-0.13.6-20200404

**Pull request merged**
