### PR TITLE
adding quickcheck-laws, smolder, list-zipper and slides

### PR DESCRIPTION
**Pull request by soupi**

### CODE REVIEW

**Comment by paf31** [comment]
Can you please run this through `jq -S` and sort the lists of dependencies?

**Comment by sudhirvkumar** [comment]
@paf31 `jq` is this https://stedolan.github.io/jq/ ?

Can we add the instructions to send PR in the README.md file? so that we can point people to the instructions before they send PRs?

**Comment by soupi** [comment]
I have made the changes.

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
