### PR TITLE
Added typelevel-codec-json

### PR DESCRIPTION
**Pull request by JordanMartinez**
Pending purescript/registry#179

### CODE REVIEW

**Comment by thomashoneyman** [comment]
@f-f do we have restrictions on case sensitivity?

**Comment by JordanMartinez** [comment]
Ah... I think this is the second time this has happened. So, I think we do.

**Comment by f-f** [comment]
@thomashoneyman @JordanMartinez I introduced a check recently, in https://github.com/purescript/package-sets/pull/941, where we verify that the URL here in package-set matches the one in the registry files. It can be made case insensitive if need be

**Comment by JordanMartinez** [comment]
This library didn't do what I thought it would, so I'm actually glad it wasn't added to the registry.

**Pull request closed without merging**
