### PR TITLE
 First small set for 0.15

### PR DESCRIPTION
**Pull request by JordanMartinez**
The `prepare-0.15` branch will be the main target for merging v0.15.0-compatible packages into the initial v0.15.0-compatible package set. This is similar to what we did in the `v0.14.0` ecosystem update (see #816). Right now, this set will not function until the `core` libraries are updated. We'll then add the contrib, web, and node libraries to this package set later. 

Some libraries will work immediately after their dependencies compile. We can add those packages back to the package set once that occurs

Other libraries will work once their dependencies compile AND the author updates the library due to breaking changes.

This PR should not be used to quickly catch via CI any issues across the core, contrib, web, and node libraries as we update the ecosystem (e.g. #799). Rather, a separate PR can be created that triggers CI to check for specific issues until they are resolved.

### CODE REVIEW

**Comment by thomashoneyman** [comment]
We'll need this before CI will build: https://github.com/purescript/registry/pull/359

**Comment by JordanMartinez** [comment]
In the last breaking release, we used a package set to verify that all core, contrib, web, and node libraries still compiled as we came across issues in the Coercible PR. However, this repo depends on something outside of core, `easy-purescript-nix`, which does not yet include the alpha release in its list of `purs`. https://github.com/justinwoo/easy-purescript-nix/pull/187 added the alpha 01 release, but wasn't merged and did not get any feedback. 

Is there a way to bypass this on our side? I'm not sure whether an alpha release should be in `easy-purescript-nix`, but this PR won't even start to compile until we can use `v0.15.0` in CI.

**Comment by thomashoneyman** [comment]
As a stopgap solution we can point to the fork instead of `easy-purescript-nix` directly. In the long term it really would be better not to depend on that external repository for anything in core.

**Comment by JordanMartinez** [comment]
How do I pre-compute the sha256 hash? I tried using `nix-fetch-git` by running [this script](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/fetchgit/nix-prefetch-git) locally.

**Comment by thomashoneyman** [comment]
I think you're looking for `nix-prefetch-git`:

```console
λ nix-prefetch-git https://github.com/jordanmartinez/easy-purescript-nix
Initialized empty Git repository in /private/var/folders/yp/8s4nn7xs4nn2y854d46lqf680000gn/T/git-checkout-tmp-HJjQ5T7H/easy-purescript-nix/.git/
remote: Enumerating objects: 54, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 54 (delta 18), reused 24 (delta 2), pack-reused 0
Unpacking objects: 100% (54/54), 36.02 KiB | 223.00 KiB/s, done.
From https://github.com/jordanmartinez/easy-purescript-nix
 * branch            HEAD       -> FETCH_HEAD
Switched to a new branch 'fetchgit'
removing `.git'...

git revision is 3630943b74f681289ed87a0ed6c3e502556ddebb
path is /nix/store/irjdyrz88m9c96k13pqfdyqny4lgk5ii-easy-purescript-nix
git human-readable version is -- none --
Commit date is 2022-02-14 09:31:58 +0200
hash is 1i7zqda52npklj3d7pq80zw5rfjjzdqpl5bdrsp6vchg5frgj6ky
{
  "url": "https://github.com/jordanmartinez/easy-purescript-nix",
  "rev": "3630943b74f681289ed87a0ed6c3e502556ddebb",
  "date": "2022-02-14T09:31:58+02:00",
  "path": "/nix/store/irjdyrz88m9c96k13pqfdyqny4lgk5ii-easy-purescript-nix",
  "sha256": "1i7zqda52npklj3d7pq80zw5rfjjzdqpl5bdrsp6vchg5frgj6ky",
  "fetchLFS": false,
  "fetchSubmodules": false,
  "deepClone": false,
  "leaveDotGit": false
}
```

**Comment by thomashoneyman** [comment]
I think you need to have your `master` branch in your fork have the code currently in the `prepare-0.15` branch, unless I'm mistaken and there's a way to point at the branch via Nix. Right now these prefetches are going to your master branch.

**Comment by JordanMartinez** [comment]
Alright! CI is failing, but it's only because `arrays` doesn't compile yet, which is what we're currently on. There's some other warnings, but we'll deal with them separately.

**Comment by JordanMartinez** [comment]
`MonadZero` class and instances were removed. Just verifying that the package set still builds.

**Comment by JordanMartinez** [comment]
CI is failing because the registry URL for colors was changed due to the transfer. See https://github.com/purescript/package-sets/runs/5660079314?check_suite_focus=true#step:5:401

Fix in https://github.com/purescript/registry/pull/371

**Comment by JordanMartinez** [comment]
Restarting CI now that `purescript-uri` has been fixed.

**Comment by JordanMartinez** [comment]
K, if we drop `math` from the package set since it will be deprecated, we get these errors:
```
[1/10 ModuleNotFound] .spago/colors/main/src/Color.purs:81:1

  81  import Math (Radians, abs, atan2, cos, pi, pow, sin, sqrt, (%))
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  Module Math was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

[2/10 ModuleNotFound] .spago/datetime/master/src/Data/Interval/Duration/Iso.purs:24:1

  24  import Math as Math
      ^^^^^^^^^^^^^^^^^^^
  
  Module Math was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

[3/10 ModuleNotFound] .spago/datetime/master/src/Data/Time.purs:21:1

  21  import Math as Math
      ^^^^^^^^^^^^^^^^^^^
  
  Module Math was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

[4/10 ModuleNotFound] .spago/formatters/main/src/Data/Formatter/Number.purs:32:1

  32  import Math as Math
      ^^^^^^^^^^^^^^^^^^^
  
  Module Math was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

[5/10 ModuleNotFound] .spago/lcg/master/src/Random/LCG.purs:19:1

  19  import Math ((%))
      ^^^^^^^^^^^^^^^^^
  
  Module Math was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

[6/10 ModuleNotFound] .spago/minibench/master/src/Performance/Minibench.purs:23:1

  23  import Math (max, min, sqrt)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  Module Math was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

[7/10 ModuleNotFound] .spago/parsing/main/src/Text/Parsing/Parser/Token.purs:45:1

  45  import Math (pow)
      ^^^^^^^^^^^^^^^^^
  
  Module Math was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

[8/10 ModuleNotFound] .spago/quickcheck/master/src/Test/QuickCheck/Gen.purs:55:1

  55  import Math ((%))
      ^^^^^^^^^^^^^^^^^
  
  Module Math was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

[9/10 ModuleNotFound] .spago/uint/main/src/Data/UInt.purs:43:1

  43  import Math (ceil, floor, round) as Math
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  Module Math was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

[10/10 ModuleNotFound] .spago/web-file/master/src/Web/File/Blob.purs:19:1

  19  import Math (round)
      ^^^^^^^^^^^^^^^^^^^
  
  Module Math was not found.
  Make sure the source file exists, and that it has been provided as an input to the compiler.

           Src   Lib   All
Warnings   0     0     0  
Errors     0     10    10 
[error] Failed to build.
```

**Comment by JordanMartinez** [comment]
PRs for the `math` stuff are:
- https://github.com/purescript-contrib/purescript-colors/pull/54
- https://github.com/purescript/purescript-datetime/pull/94
- https://github.com/purescript-contrib/purescript-formatters/pull/80
- https://github.com/purescript/purescript-lcg/pull/16
- https://github.com/purescript/purescript-minibench/pull/23
- https://github.com/purescript-contrib/purescript-parsing/pull/167
- https://github.com/purescript/purescript-quickcheck/pull/133
- https://github.com/purescript-contrib/purescript-uint/pull/21
- https://github.com/purescript-web/purescript-web-file/pull/20

**Comment by JordanMartinez** [comment]
Restarting CI

**Comment by JordanMartinez** [comment]
CI builds. I think we have our first `0.15.0` package set.

**Comment by JordanMartinez** [comment]
Once these two PRs are merged, the package set builds again:
- https://github.com/purescript-contrib/purescript-formatters/pull/82
- https://github.com/purescript-contrib/purescript-uri/pull/73

**Comment by JordanMartinez** [comment]
The only package that broke due to https://github.com/purescript-node/purescript-node-streams/pull/41 was `sunde`.

**Comment by JordanMartinez** [comment]
We've been building this package set using the `0.15.0-alpha-02` release. I've updated it to now use the `0.15.0-alpha-07` release.

**Comment by JordanMartinez** [comment]
We'll need to update `affjax-web` and `affjax-node` for these changes:
- https://github.com/purescript-contrib/purescript-affjax-web/pull/3/commits/a148ae68d96db9c907d871db93060ebbd183fd1e
- https://github.com/purescript-contrib/purescript-affjax-node/pull/2/commits/f711f711e1738bba791b155bed974672ed6769c2

**Comment by thomashoneyman** [comment]
@JordanMartinez done!

**Comment by JordanMartinez** [comment]
Thanks!

**Comment by JordanMartinez** [comment]
Once this gets merged, we should update the `easy-ps` code to refer to the original repo, not my fork.

**Review by thomashoneyman — APPROVED** [review]

**Pull request merged**
