### PR TITLE
Add tweag group and unlift v1.0.0

### PR DESCRIPTION
**Pull request by jhbertra**

### CODE REVIEW

**Comment by thomashoneyman** [comment]
@jhbertra Sorry for the hassle — still need that generated packages.json!

**Comment by jhbertra** [comment]
🙃 Lots of manual steps

**Comment by thomashoneyman** [comment]
Yes, it's a huge hassle 😞 — fortunately, publishing a package and then adding it to the package sets and pushing it to Pursuit are automated as part of the new PureScript registry, which is tracked over at https://github.com/purescript/registry

**Comment by jhbertra** [comment]
Yes, I saw that yesterday when I added this package to the registry.  I assume this is still a work in progress though?

**Comment by jhbertra** [comment]
The current process isn't too onerous, it wasn't too difficult to pick it up - and I suspect I'll get more practiced at it. I am looking forward to the publishing infrastructure getting more streamlined and automated though!

**Pull request merged**
