### PR TITLE
Add int-53, redis-client and redis-hotqueue

### PR DESCRIPTION
**Pull request by paluh**
Unfortunately I wasn't able to run `psc-package verify` (I'm getting enigmatic `does not exist`). On the other hand I'm using this version package-sets and the above packages in my current project it and it compiles without any problems :-)

### CODE REVIEW

**Comment by f-f** [comment]
@paluh thank you for this! It seems like your latest commit is missing some packages that are required to build the new ones you added.

And thanks for noting that our instructions were outdated (`psc-package` had a breaking change in https://github.com/purescript/psc-package/pull/158), I opened #577 to fix the issue and switch the instructions to use Spago instead

**Comment by paluh** [comment]
@f-f Thanks for a lot for your feedback and sorry that I've missed out that my second commit had broke the CI build.

 > I opened #577 to fix the issue and switch the instructions to use Spago instead

It is really good to know. Thanks!

I'm only not sure what the current status of this PR is. I'm bit lost regarding your last commit which is visible above. Could you please tell me if it is included already in this PR and fixes the issue with missing dependencies or should I push the fix myself?

**Comment by f-f** [comment]
@paluh if you're done adding packages then this PR is good to go. Can I merge?

The reason why your commit broke CI is that you upgraded `polyform` to `0.8.2`, which included a dependency on `validation`, which the previous version `0.8.0` did not include. I fixed this independently in #575, which is why merging `master` in here fixed the build

**Comment by paluh** [comment]
> (...)￼ if you don't have any more packages to add then this PR is good to go. Can I merge?

Yeah, sure. Thanks!

P.S.
I'm going to push more of our "core" libs like postgresql-client, selda etc. but I will open a separate PR fot this.

**Comment by f-f** [comment]
Thank you! :slightly_smiling_face:

**Pull request merged**
