### PR TITLE
Add elmish-html, bump elmish to 0.3.1

### PR DESCRIPTION
**Pull request by fsoikin**

### CODE REVIEW

**Comment by thomashoneyman** [comment]
Looks like there's [not a v0.2.0 tag for elmish-html](https://github.com/collegevine/purescript-elmish-html/releases) and that's why CI is failing

**Comment by fsoikin** [comment]
Yep, already fixed.

**Comment by thomashoneyman** [comment]
https://github.com/purescript/package-sets/releases/tag/psc-0.13.8-20201223

**Comment by fsoikin** [comment]
Thank you very much!

**Pull request merged**
