### PR TITLE
Add routing v.8.0.0, spec-quickcheck v3.0.0, record-extra v1.0.0, errors v4.0.1, web-socket v1.0.0.

### PR DESCRIPTION
**Pull request by Rembane**
What it says on the tin. `psc-package verify routing` worked out well.

### CODE REVIEW

**Comment by justinwoo** [comment]
Even as the author of record-extra I don't think I want most people to use that library. The others look fine to include.

**Comment by Rembane** [comment]
@justinwoo Sweet, thank you. If I still need record-extra I'll get back to you. :)

**Comment by Rembane** [comment]
I added the packages errors and web-socket too. These are all packages I need in my current project, so I won't add any more commits to this pull request, unless asked to.

Should I remove the record-extra package?

**Comment by justinwoo** [comment]
Sorry for the late response, didn't realize you commented. Yes, please remove record-extra, since it's more confusing to have than not.

**Comment by Rembane** [comment]
I moved the relevant parts to this pull request instead. https://github.com/purescript/package-sets/pull/200

**Pull request closed without merging**
