### PR TITLE
Update `simple-json` to v1.0.0

### PR DESCRIPTION
**Pull request by joneshf**
Made the change through GitHub UI. Assuming travis is good, it should be good though, right?

### CODE REVIEW

**Comment by paf31** [comment]
👍 Yes, thanks!

**Comment by joneshf** [comment]
Thanks! Can we get a tag?

**Comment by paf31** [comment]
Absolutely. We probably need a tool to do package set diffs for the release notes at some point 😄

**Comment by paf31** [comment]
https://github.com/purescript/package-sets/releases/tag/psc-0.11.6-09272017

**Pull request merged**
