### PR TITLE
Update affjax to 11.0.0

### PR DESCRIPTION
**Pull request by andys8**
## Changes

- affjax (slamdata/purescript-affjax) ✖ v10.1.0 -> v11.0.0

Related to #723 and #725 

**Update**: Description heavily updated.

### CODE REVIEW

**Comment by andys8** [comment]
It looks like updating `purescript-affjax` will break `purescript-simple-ajax`. 

I'm don't know how this is handled in general.
I provided a fix https://github.com/dariooddenino/purescript-simple-ajax/pull/6


```
Compiling Sijidou
[info] Build succeeded.
[info] Successfully verified "sijidou"
[info] Installing 1 dependencies.
[info] Searching for packages cache metadata..
[info] Recent packages cache metadata found, using it..
[info] Installing "simple-ajax"
[info] Installation complete.
[info] Verifying package "simple-ajax"
Error found:
in module Simple.Ajax
at .spago/simple-ajax/v2.0.0/src/Simple/Ajax.purs:109:24 - 111:38 (line 109, column 24 - line 111, column 38)

  Could not match type

    ( timeout :: Maybe Milliseconds
    ...
    )

  with type

    ( ... )


while trying to match type
                             ( timeout :: Maybe Milliseconds
                             ...
                             )

  with type
              ( ... )

while solving type class constraint

  Prim.Row.Nub t0
               ( content :: Maybe RequestBody
               , headers :: Array RequestHeader
               , method :: Either Method CustomMethod
               , password :: Maybe String
               , responseFormat :: ResponseFormat String
               , url :: String
               , username :: Maybe String
               , withCredentials :: Boolean
               )

while inferring the type of merge { responseFormat: string
                                  , headers: [ ...
                                             ]
                                  }
in value declaration defaultSimpleRequest

where t0 is an unknown type

See https://github.com/purescript/documentation/blob/master/errors/TypesDoNotUnify.md for more information,
Compiling Simple.Ajax.Errors
Compiling Simple.Ajax
or to contribute content related to this error.


[error] Failed to build.
```

**Comment by andys8** [comment]
I'd suggest considering this blocked, and proceed with https://github.com/purescript/package-sets/pull/725

**Comment by andys8** [comment]
Rebased on `master` because https://github.com/purescript/package-sets/pull/725 was merged

**Comment by JordanMartinez** [comment]
I'm guessing this should be considered blocked until `simple-ajax` is updated?

**Comment by andys8** [comment]
Yes

**Comment by thomashoneyman** [comment]
In general we try to let package authors have 2 weeks to respond before their package is dropped from the set due to a breaking change in a dependency, unless that dependency change will affect a _lot_ of libraries, in which case we allow for longer.

**Comment by dariooddenino** [comment]
I have merged the pr and published a new version of simple-ajax. Let me know if I have to do anything else, thanks! :)

**Comment by andys8** [comment]
Thanks for the quick response @dariooddenino

**Review by f-f — APPROVED** [review]
Thank you! :clap:

**Pull request merged**
