### PR TITLE
Add parsing-repetition (#681)

### PR DESCRIPTION
**Pull request by markfarrell**
https://github.com/purescript/registry/pull/60

### CODE REVIEW

**Comment by thomashoneyman** [comment]
@markfarrell Do you mind re-running `nix-shell --command make` in the root of package sets in your fork and pushing those changes to this branch? I believe that will pass CI.

**Comment by markfarrell** [comment]
> @markfarrell Do you mind re-running `nix-shell --command make` in the root of package sets in your fork and pushing those changes to this branch? I believe that will pass CI.

I re-ran `nix-shell --command make`. Good now?

**Comment by f-f** [comment]
@markfarrell that works, but it looks like the tag you specified (`v0.0.6`) doesn't exist?

**Comment by markfarrell** [comment]
I can’t confirm. Tag v0.0.6 exists and published to pursuit afaik?

**Comment by f-f** [comment]
@markfarrell if doesn't exist on GitHub, which is necessary for CI to pass and package managers to work.

**Comment by markfarrell** [comment]
My bad. Fixed a typo?

**Review by f-f — APPROVED** [review]
Looks great now, thanks!

**Pull request merged**
