### PR TITLE
Add affjax

### PR DESCRIPTION
**Pull request by MichaelXavier**

### CODE REVIEW

**Comment by paf31** [comment]
When you rebase this, could you please resort the file? I usually pipe it through `jq -S`.

**Comment by MichaelXavier** [comment]
@paf31 ok, didn't know how you wanted that done. So to be clear, I should in this branch (and my other PR for pux) run `git rebase origin/master` and then create another commit sorting the file?

**Comment by paf31** [comment]
No need for a new PR, I just meant could you please resort after resolving conflicts and before your next commit?

**Comment by MichaelXavier** [comment]
@paf31 ok, I resolved with master. I guess for #84 I'll wait for this to merge to master and do the same thing. Git's merge strategy completely mangles these JSON files, so its easier to just take the new key, merge it in and then do the sort.

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
