### PR TITLE
Adding purescript-promises

### PR DESCRIPTION
**Pull request by mwalkerwells**
Ran `psc-package verify` and everything checks 👌🏻

https://github.com/thimoteus/purescript-promises

### CODE REVIEW

**Comment by f-f** [comment]
Hi @mwalkerwells, thanks for the PR!

Since #271 the `packages.json` is not the main source of truth anymore, but it gets generated from [the Dhall files](https://github.com/purescript/package-sets/tree/master/src). So in this case to make CI pass you should add the new package [here](https://github.com/purescript/package-sets/blob/master/src/groups/Thimoteus.dhall)

There were supposed to be [instructions about this](https://github.com/purescript/package-sets#how-to-contribute-to-this-package-set) in the README, but it looks like something got lost in the refactoring, so they are now a bit unclear

**Comment by mwalkerwells** [comment]
Ah, gotcha! I was following the instructions here: https://github.com/purescript/psc-package/blob/master/docs/maintenance.md

**Comment by f-f** [comment]
@mwalkerwells thanks for the heads up, I'll fix those docs too 🙂

**Comment by mwalkerwells** [comment]
Need to wait for this to be accepted by @Thimoteus + have the package version bumped to v3.0.1 

https://github.com/Thimoteus/purescript-promises/pull/9

**Comment by f-f** [comment]
@mwalkerwells sounds good!
Note though that you'll need to commit also the changes to the `packages.json` (it should be enough to run `make` to get the new one now that you changed the Dhall files)

**Comment by mwalkerwells** [comment]
Done 👌🏻

**Comment by mwalkerwells** [comment]
@f-f Not getting a response, mind accepting this PR with my fork for now? I'll submit another PR once we fix his breaking build.

**Comment by f-f** [comment]
@mwalkerwells I'd prefer to include the upstream in the package-set if possible (also because we already include one of their packages), so let's wait some days, as the maintainer might be busy.

If you're using psc-package in the meanwhile you can point the tool at your fork of package-sets, by specifying the repo URL in the `source` key of your configuration

**Comment by mwalkerwells** [comment]
Will do 👌🏻 Just reverted for now... We wait... 🙏🏻

**Comment by mwalkerwells** [comment]
@f-f PR accepts & all should be good now

**Comment by justinwoo** [comment]
Thanks

**Pull request merged**
