### PR TITLE
Add gl-matrix

### PR DESCRIPTION
**Pull request by dirkz**
Add a purescript wrapper to glmatrix.net

### CODE REVIEW

**Comment by f-f** [comment]
It looks like CI is failing because the packages you're adding here have not been added to [the registry](https://github.com/purescript/registry/blob/master/new-packages.json), could you add them first?

**Comment by dirkz** [comment]
Thanks for the heads up. Will add it to the registry, then remove test dependencies from the build, then try again.

**Comment by thomashoneyman** [comment]
@dirkz you should now be able to make that update

**Comment by dirkz** [comment]
Updated the lib to v2.0.1, now without quickcheck. All good from my side.

**Review by f-f — APPROVED** [review]

**Pull request merged**
