### PR TITLE
Add nano-id v1.0.0

### PR DESCRIPTION
**Pull request by eikooc**

### CODE REVIEW

**Comment by thomashoneyman** [comment]
Hi @eikooc! Since this is your first package, you'll need to add yourself to the main `package.dhall` file that lists out the various groups. You can just copy/paste the last line and change it to point to the name of your new group file.

https://github.com/purescript/package-sets/blob/master/src/packages.dhall

**Comment by eikooc** [comment]
Okay, I should have done that now. Thanks @thomashoneyman

**Comment by PureFunctor** [comment]
Hey, @eikooc the build is currently failing because `nano-id` hasn't been added to the https://github.com/purescript/registry yet. You'll need to add your project in the `new-packages.json` file there.

**Comment by thomashoneyman** [comment]
@eikooc It looks like you haven't released a v1.0.0 of this package; you need to have a tag corresponding with that version in order to record this in the package sets.

https://github.com/eikooc/nano-id/tags

**Pull request merged**
