### PR TITLE
Add halogen-hooks

### PR DESCRIPTION
**Pull request by thomashoneyman**
This small update adds the halogen-hooks package to my group in the package sets.

### CODE REVIEW

**Comment by f-f** [comment]
@thomashoneyman could you run `make`? (possibly inside `nix-shell`)

**Comment by thomashoneyman** [comment]
Should I run anything more specific than this?

```sh
[nix-shell:~/Desktop/package-sets]$ make
formatted dhall files
generated to packages.json
```

^ that's on my `patch-1` branch in my fork.

**Comment by f-f** [comment]
@thomashoneyman what you're running is good, but you should commit the `packages.json` too

**Comment by thomashoneyman** [comment]
Oh! I misunderstood. Updated!

**Comment by f-f** [comment]
Thank you! :slightly_smiling_face:

**Pull request merged**
