### PR TITLE
parsing v7.0.0, formatters v6.0.0, graphql-client v7.0.0

### PR DESCRIPTION
**Pull request by jamesdbrock**
parsing v7.0.0, formatters v6.0.0, graphql-client v7.0.0

Disable
* markfarrell/parsing-hexidecimal
* markfarrell/parsing-uuid

### CODE REVIEW

**Comment by jamesdbrock** [comment]
https://github.com/purescript-contrib/purescript-formatters/pull/76

**Comment by jamesdbrock** [comment]
Should I comment out __formatters__ from the package-set and then we add __formatters__ back in when it upgrades?

**Comment by jamesdbrock** [comment]
> get the formatters PR merged and then update both in package sets at once?

Sounds good.

**Comment by thomashoneyman** [comment]
@jamesdbrock I think it should be graphql-client v7.0.0

**Comment by jamesdbrock** [comment]
Ok I think this is ready to go now. I'll open issues with @markfarrell when it's merged so he can upgrade his packages.

**Review by thomashoneyman — APPROVED** [review]

**Comment by thomashoneyman** [comment]
I've merged this, and yea we should open issues (or even pull requests if it's simple) against the two disabled libraries. Thanks @jamesdbrock!

**Pull request merged**
