### PR TITLE
Update halogen-hooks-extra to 0.7.1

### PR DESCRIPTION
**Pull request by milesfrain**

### CODE REVIEW

**Comment by milesfrain** [comment]
I'm guessing I need to install nix to suggest version bumps.

Might be good to add a section in the [contributors guide](https://github.com/purescript/package-sets/blob/master/CONTRIBUTING.md#how-to-add-a-package-to-the-set) about "updating packages".

I assume a future plan for the registry is to automate the process of picking up the latest available releases.

@JordanMartinez to check if halogen-hooks-extra v0.7.1 is ready for the package set.

**Comment by JordanMartinez** [comment]
Yeah. The current library still builds on the `0.4.2` version of halogen hooks.

**Comment by f-f** [comment]
It looks like CI is failing because the `packages.json` was not updated - could you run `nix-shell --run 'make'` and commit all the files?

**Comment by f-f** [comment]
@milesfrain re automatic updates: we had automation running to update things automatically here (temporarily out of service), and yes, with the registry it will be much easier to automate this.

**Comment by JordanMartinez** [comment]
Thanks Miles!

**Pull request merged**
